conditinal  workflow based on jobs

diff --git a/.github/workflows/first-workflow.yml b/.github/workflows/first-workflow.yml
--- a/.github/workflows/first-workflow.yml
+++ b/.github/workflows/first-workflow.yml
@@ -12,5 +12,5 @@ jobs:
       - name: Bye Github Action
         run: echo "Bye github action"
         #  write below code for check conditionally, exit 1 means code fial with exit 0  then code pass
-      - name: fail job intentinolly
-        run: exit 1
+      # - name: fail job intentinolly
+      #   run: exit 1
